# .github/workflows/dependency-graph.yml
name: Update Dependency Graph
on:
  push:
    branches:
      - master # default branch of the project

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: dependency-graph-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: sbt/setup-sbt@4ed7b7ec4bfa2074fe48554c09e341267397247c # v1
      - uses: scalacenter/sbt-dependency-submission@1cc96a7038ea2b014c200c1dae3a0cc92293b91d # v3.2.2
