# .github/workflows/dependency-graph.yml
name: Update Dependency Graph
on:
  push:
    branches:
      - master # default branch of the project

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: dependency-graph-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: sbt/setup-sbt@v1
      - uses: scalacenter/sbt-dependency-submission@v3
